### ISSUE TITLE
BootUSBE5440.zip --> can't download

### ISSUE THREAD

**Issue by schneckeeee** [Sipylus/Dell-Latitude-E5440#4]
hallo!

i need a username/password to download your file "BootUSBE5440.zip" from the gixxer/dualboot server, but it's not possible to register. any suggestions?

thx

**Comment by nyhtml** [comment]
I can unlock it for an hour but what parts do you need as I could put those here.

**Comment by SamuelPalubaCZ** [comment]
@nyhtml PLZ DO IT!!!

**Comment by nyhtml** [comment]
One hour 15 minutes only. Relocks at 10:30 AM ET.
