### ISSUE TITLE
How to Downland Boot Pack?

### ISSUE THREAD

**Issue by SamuelPalubaCZ** [Sipylus/Dell-Latitude-E5440#5]
Hi can i ask you how to dowland this i like your yt

**Comment by nyhtml** [comment]
It's included with the laptop.
If you didn't have one, the laptop wasn't from me and may not be fully compatible.
I unlocked it for an hour and 15 minutes and relocked it at 10:30 AM ET.
Hopefully, you got it in that time.

**Comment by SamuelPalubaCZ** [comment]
😥😌 No... But thx for your time and work... 
Can you do it now or 17:00 PRAGUE Time (11:00 NEW YORK, 10:00 TEXAS) 🙏 
Thank you again Thank you for your time and patience.

**Comment by nyhtml** [comment]
It should be fine now.

<img width="479" alt="E5540" src="https://github.com/Sipylus/Dell-Latitude-E5440/assets/2177262/bc40e356-a308-4f10-83ef-7842b5c5f4f1">
